module.exports = [
  {
    key: process.env.realdev,
    discordID: "0",
    nameColor: "#00ffff",
    class: "realdeveloper",
    infiniteLevelUp: true,
    allowSpam: true,
    name: "unnamed#0000",
    note: "Developer with chat commands",
  },
  {
    key: process.env.dev,
    discordID: "0",
    nameColor: "#00ff00",
    class: "developer",
    infiniteLevelUp: true,
    allowSpam: true,
    name: "unnamed#0000",
    note: "Developer",
  },
  {
    key: process.env.shiny,
    discordID: "0",
    nameColor: "#ffff70",
    class: "shinyMember",
    infiniteLevelUp: true,
    allowSpam: true,
    name: "unnamed#0000",
    note: "Shiny",
  },
  {
    key: process.env.hacker,
    discordID: "0",
    nameColor: "#ffaa00",
    class: "HackerMenu",
    infiniteLevelUp: true,
    allowSpam: true,
    name: "unnamed#0000",
    note: "Hacker",
  },
  {
    key: process.env.betatester,
    discordID: "0",
    nameColor: "#00ffff",
    class: "BetaTester",
    infiniteLevelUp: true,
    allowSpam: true,
    name: "unnamed#0000",
    note: "Beta Tester",
  },
  {
    key: process.env.trusted,
    discordID: "0",
    nameColor: "#aaaaaa",
    class: "trusted",
    infiniteLevelUp: false,
    allowSpam: true,
    name: "unnamed#0000",
    note: "Trusted",
  },
  {
    key: process.env.free,
    discordID: "0",
    nameColor: "#aaaaff",
    class: "freeTanksMenu",
    infiniteLevelUp: false,
    allowSpam: false,
    name: "unnamed#0000",
    note: "Free",
  },
];
